---
- name: Ruby setup
  hosts: new
  remote_user: '{{ _remote_user }}'
  become: true
  gather_facts: true
  vars:
    rbenv:
      env: user
      version: '{{ _rbenv }}'
      default_ruby: '{{ _ruby }}'
      rubies:
        - version: '{{ _ruby }}'

  roles:
    - role: zzet.rbenv
      rbenv_users:
        - '{{ _remote_user }}'

  post_tasks:
      - command: 'sudo -iu {{ _remote_user }} gem update --system'
      #  https://github.com/ansible/ansible/issues/4854